<?php

$labels['export_excel'] = 'Izvoz u Excel';
$labels['export_excel_csv'] = 'Izvoz u CSV';
$labels['export_excel_xls'] = 'Izvoz u XLS';
$labels['export_excel_xlsx'] = 'Izvoz u XLSX';
$labels['export_excel_html'] = 'Izvoz u HTML';

$labels['too_many_messages'] = 'Previše poruka odabrano za izvoz. Molimo odaberite manje od $limit poruka.';
$labels['wrong_format'] = 'Format $format nije podržan';
$labels['wrong_format'] = "Format nije podržan";

$labels['column_from'] = "Od";
$labels['column_to'] = "Za";
$labels['column_subject'] = "Naslov";
$labels['column_date'] = "Datum";
$labels['column_body'] = "Sadržaj";

$labels['exporting'] = 'Generišem excel podatke...';
