<?php
$labels['export_excel'] = 'Export to Excel';
$labels['export_excel_csv'] = 'Export to CSV';
$labels['export_excel_xls'] = 'Export to XLS';
$labels['export_excel_xlsx'] = 'Export to XLSX';
$labels['export_excel_html'] = 'Export to HTML';


$labels['too_many_messages'] = 'Too many messages selected for export. Please select less than $limit messages.';
$labels['wrong_format'] = 'Format $format is not supported';

$labels['column_from'] = "From";
$labels['column_to'] = "To";
$labels['column_subject'] = "Subject";
$labels['column_date'] = "Date";
$labels['column_body'] = "Body";

$labels['exporting'] = 'Exporting excel data...';